-- =====================================================
-- SUPABASE DATABASE SETUP FOR SGAC COLLEGE WEBSITE
-- =====================================================
-- Go to Supabase Dashboard > SQL Editor and run this script
-- =====================================================

-- Create news table
CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    date VARCHAR(50),
    icon VARCHAR(50) DEFAULT 'fa-bullhorn',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create events table
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    date VARCHAR(50),
    icon VARCHAR(50) DEFAULT 'fa-calendar',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create downloads table
CREATE TABLE IF NOT EXISTS public.downloads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    link VARCHAR(500),
    icon VARCHAR(50) DEFAULT 'fa-download',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create announcements table
CREATE TABLE IF NOT EXISTS public.announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create carousel table
CREATE TABLE IF NOT EXISTS public.carousel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    img VARCHAR(500) NOT NULL,
    alt VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- =====================================================
-- INSERT DEFAULT DATA
-- =====================================================

-- Insert default news
INSERT INTO public.news (title, date, icon) VALUES 
('International Virtual Conference on Innovation and Intelligence in Computing System', 'May 02, 2022', 'fa-university'),
('E-Workshop on Writing Skills Organised by English Department', 'July 03 & July 05', 'fas fa-book-open'),
('E-Quiz Organised By Computer Science Department', 'May 21 & May 22', 'fa-laptop'),
('E-Quiz Organised By National Service Scheme Club', 'May 26 & May 27', 'fas fa-running');

-- Insert default events
INSERT INTO public.events (title, date, icon) VALUES 
('Annual Day Celebration', 'March 15, 2025', 'fa-calendar'),
('Sports Day Events', 'February 28, 2025', 'fa-trophy');

-- Insert default downloads
INSERT INTO public.downloads (title, link, icon) VALUES 
('Bonafide Certificate', 'Documents/Forms/Bonafide.pdf', 'fa-download'),
('Attendance Certificate', 'Documents/Forms/Attendance.pdf', 'fa-download'),
('Academic Calendar 2024-2025', 'Documents/calendar/2024-2025 calendar.pdf', 'fa-download');

-- Insert default announcements
INSERT INTO public.announcements (text) VALUES 
('RankList for I Year PG Admission [2025-2026] Released'),
('Special Quota Counselling on 02/06/2025 & 03/06/2025');

-- Insert default carousel images
INSERT INTO public.carousel (img, alt) VALUES 
('https://sgacrmd.edu.in/assets/carousel/7-01-2026/1.jpg', 'College Campus'),
('https://sgacrmd.edu.in/assets/carousel/7-01-2026/2.jpg', 'Laboratory'),
('https://sgacrmd.edu.in/assets/carousel/7-01-2026/3.jpg', 'Library');

-- =====================================================
-- ENABLE ROW LEVEL SECURITY (RLS)
-- =====================================================

-- Enable RLS on all tables
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.downloads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carousel ENABLE ROW LEVEL SECURITY;

-- Create policies to allow public read access
CREATE POLICY "Allow public read access for news" ON public.news FOR SELECT USING (true);
CREATE POLICY "Allow public read access for events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Allow public read access for downloads" ON public.downloads FOR SELECT USING (true);
CREATE POLICY "Allow public read access for announcements" ON public.announcements FOR SELECT USING (true);
CREATE POLICY "Allow public read access for carousel" ON public.carousel FOR SELECT USING (true);

-- Create policies to allow authenticated insert/update/delete
-- (For admin panel - you may want to restrict this further)
CREATE POLICY "Allow authenticated insert for news" ON public.news FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated update for news" ON public.news FOR UPDATE USING (true);
CREATE POLICY "Allow authenticated delete for news" ON public.news FOR DELETE USING (true);

CREATE POLICY "Allow authenticated insert for events" ON public.events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated update for events" ON public.events FOR UPDATE USING (true);
CREATE POLICY "Allow authenticated delete for events" ON public.events FOR DELETE USING (true);

CREATE POLICY "Allow authenticated insert for downloads" ON public.downloads FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated update for downloads" ON public.downloads FOR UPDATE USING (true);
CREATE POLICY "Allow authenticated delete for downloads" ON public.downloads FOR DELETE USING (true);

CREATE POLICY "Allow authenticated insert for announcements" ON public.announcements FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated update for announcements" ON public.announcements FOR UPDATE USING (true);
CREATE POLICY "Allow authenticated delete for announcements" ON public.announcements FOR DELETE USING (true);

CREATE POLICY "Allow authenticated insert for carousel" ON public.carousel FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated update for carousel" ON public.carousel FOR UPDATE USING (true);
CREATE POLICY "Allow authenticated delete for carousel" ON public.carousel FOR DELETE USING (true);

-- =====================================================
-- DONE!
-- =====================================================

SELECT 'Database tables created and configured successfully!' AS status;
