-- =====================================================
-- COMPLETE SUPABASE DATABASE SETUP
-- Run this in Supabase SQL Editor
-- =====================================================

-- =====================================================
-- 1. NEWS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS public.news (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    date text,
    icon text DEFAULT 'fa-bullhorn',
    created_at timestamptz DEFAULT now()
);

-- =====================================================
-- 2. EVENTS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    date text,
    icon text DEFAULT 'fa-calendar',
    created_at timestamptz DEFAULT now()
);

-- =====================================================
-- 3. DOWNLOADS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS public.downloads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    link text,
    icon text DEFAULT 'fa-download',
    created_at timestamptz DEFAULT now()
);

-- =====================================================
-- 4. CAROUSEL TABLE (Home Page Slider Images)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.carousel (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    img text NOT NULL,
    alt text,
    created_at timestamptz DEFAULT now()
);

-- =====================================================
-- 5. ANNOUNCEMENTS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS public.announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- =====================================================
-- 6. FACULTY TABLE (For all departments)
-- =====================================================
CREATE TABLE IF NOT EXISTS public.faculty (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_key text NOT NULL,
    name text NOT NULL,
    designation text,
    qualification text,
    email text,
    phone text,
    image text,
    resume text,
    created_at timestamptz DEFAULT now()
);

-- =====================================================
-- 7. DEPARTMENT INFO TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS public.departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_key text UNIQUE NOT NULL,
    name text,
    icon text,
    about text,
    vision text,
    mission text,
    hod_name text,
    hod_designation text,
    hod_qualification text,
    created_at timestamptz DEFAULT now()
);

-- =====================================================
-- 8. ACTIVITIES TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS public.activities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    date text,
    dept_key text,
    created_at timestamptz DEFAULT now()
);

-- =====================================================
-- 9. ACHIEVEMENTS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS public.achievements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text,
    student_name text,
    dept_key text,
    created_at timestamptz DEFAULT now()
);

-- =====================================================
-- 10. GALLERY TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS public.gallery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_key text,
    img text NOT NULL,
    caption text,
    created_at timestamptz DEFAULT now()
);

-- =====================================================
-- ENABLE ROW LEVEL SECURITY
-- =====================================================
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.downloads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.carousel ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.faculty ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- CREATE POLICIES (Public Read Access)
-- =====================================================
CREATE POLICY "news_read" ON public.news FOR SELECT USING (true);
CREATE POLICY "news_insert" ON public.news FOR INSERT WITH CHECK (true);
CREATE POLICY "news_update" ON public.news FOR UPDATE USING (true);
CREATE POLICY "news_delete" ON public.news FOR DELETE USING (true);

CREATE POLICY "events_read" ON public.events FOR SELECT USING (true);
CREATE POLICY "events_insert" ON public.events FOR INSERT WITH CHECK (true);
CREATE POLICY "events_update" ON public.events FOR UPDATE USING (true);
CREATE POLICY "events_delete" ON public.events FOR DELETE USING (true);

CREATE POLICY "downloads_read" ON public.downloads FOR SELECT USING (true);
CREATE POLICY "downloads_insert" ON public.downloads FOR INSERT WITH CHECK (true);
CREATE POLICY "downloads_update" ON public.downloads FOR UPDATE USING (true);
CREATE POLICY "downloads_delete" ON public.downloads FOR DELETE USING (true);

CREATE POLICY "carousel_read" ON public.carousel FOR SELECT USING (true);
CREATE POLICY "carousel_insert" ON public.carousel FOR INSERT WITH CHECK (true);
CREATE POLICY "carousel_update" ON public.carousel FOR UPDATE USING (true);
CREATE POLICY "carousel_delete" ON public.carousel FOR DELETE USING (true);

CREATE POLICY "announcements_read" ON public.announcements FOR SELECT USING (true);
CREATE POLICY "announcements_insert" ON public.announcements FOR INSERT WITH CHECK (true);
CREATE POLICY "announcements_update" ON public.announcements FOR UPDATE USING (true);
CREATE POLICY "announcements_delete" ON public.announcements FOR DELETE USING (true);

CREATE POLICY "faculty_read" ON public.faculty FOR SELECT USING (true);
CREATE POLICY "faculty_insert" ON public.faculty FOR INSERT WITH CHECK (true);
CREATE POLICY "faculty_update" ON public.faculty FOR UPDATE USING (true);
CREATE POLICY "faculty_delete" ON public.faculty FOR DELETE USING (true);

CREATE POLICY "departments_read" ON public.departments FOR SELECT USING (true);
CREATE POLICY "departments_insert" ON public.departments FOR INSERT WITH CHECK (true);
CREATE POLICY "departments_update" ON public.departments FOR UPDATE USING (true);
CREATE POLICY "departments_delete" ON public.departments FOR DELETE USING (true);

CREATE POLICY "activities_read" ON public.activities FOR SELECT USING (true);
CREATE POLICY "activities_insert" ON public.activities FOR INSERT WITH CHECK (true);
CREATE POLICY "activities_update" ON public.activities FOR UPDATE USING (true);
CREATE POLICY "activities_delete" ON public.activities FOR DELETE USING (true);

CREATE POLICY "achievements_read" ON public.achievements FOR SELECT USING (true);
CREATE POLICY "achievements_insert" ON public.achievements FOR INSERT WITH CHECK (true);
CREATE POLICY "achievements_update" ON public.achievements FOR UPDATE USING (true);
CREATE POLICY "achievements_delete" ON public.achievements FOR DELETE USING (true);

CREATE POLICY "gallery_read" ON public.gallery FOR SELECT USING (true);
CREATE POLICY "gallery_insert" ON public.gallery FOR INSERT WITH CHECK (true);
CREATE POLICY "gallery_update" ON public.gallery FOR UPDATE USING (true);
CREATE POLICY "gallery_delete" ON public.gallery FOR DELETE USING (true);

-- =====================================================
-- INSERT DEFAULT DATA
-- =====================================================

-- Default News
INSERT INTO public.news (title, date, icon) VALUES 
('International Virtual Conference on Innovation and Intelligence in Computing System', 'May 02, 2022', 'fa-university'),
('E-Workshop on Writing Skills Organised by English Department', 'July 03 & July 05', 'fas fa-book-open'),
('E-Quiz Organised By Computer Science Department', 'May 21 & May 22', 'fa-laptop'),
('E-Quiz Organised By National Service Scheme Club', 'May 26 & May 27', 'fas fa-running');

-- Default Events
INSERT INTO public.events (title, date, icon) VALUES 
('Annual Day Celebration', 'March 15, 2025', 'fa-calendar'),
('Sports Day Events', 'February 28, 2025', 'fa-trophy');

-- Default Downloads
INSERT INTO public.downloads (title, link, icon) VALUES 
('Bonafide Certificate', 'Documents/Forms/Bonafide.pdf', 'fa-download'),
('Attendance Certificate', 'Documents/Forms/Attendance.pdf', 'fa-download'),
('Academic Calendar 2024-2025', 'Documents/calendar/2024-2025 calendar.pdf', 'fa-download');

-- Default Carousel Images
INSERT INTO public.carousel (img, alt) VALUES 
('https://sgacrmd.edu.in/assets/carousel/1.jpg', 'College Campus'),
('https://sgacrmd.edu.in/assets/carousel/2.jpg', 'Academic Block'),
('https://sgacrmd.edu.in/assets/carousel/3.jpg', 'Library'),
('https://sgacrmd.edu.in/assets/carousel/4.jpg', 'Laboratory');

-- Default Announcements
INSERT INTO public.announcements (text) VALUES 
('RankList for I Year PG Admission [2025-2026] Released'),
('Special Quota Counselling on 02/06/2025 & 03/06/2025');

-- Default Departments
INSERT INTO public.departments (dept_key, name, icon, about, vision, mission) VALUES
('tamil', 'Tamil', 'fa-language', 'Department of Tamil language and literature', 'To preserve and promote Tamil language', 'To provide quality Tamil education'),
('english', 'English', 'fa-globe', 'Department of English language and literature', 'To develop English communication skills', 'To provide quality English education'),
('mathematics', 'Mathematics', 'fa-calculator', 'Department of Mathematics', 'To excel in mathematical sciences', 'To provide quality mathematics education'),
('physics', 'Physics', 'fa-atom', 'Department of Physics', 'To promote physics education and research', 'To provide quality physics education'),
('chemistry', 'Chemistry', 'fa-flask', 'Department of Chemistry', 'To excel in chemical sciences', 'To provide quality chemistry education'),
('botany', 'Botany', 'fa-leaf', 'Department of Botany', 'To promote plant sciences', 'To provide quality botany education'),
('zoology', 'Zoology', 'fa-paw', 'Department of Zoology', 'To promote zoological sciences', 'To provide quality zoology education'),
('computer', 'Computer Science', 'fa-laptop', 'Department of Computer Science', 'To produce skilled IT professionals', 'To provide quality computer education'),
('commerce', 'Commerce', 'fa-calculator', 'Department of Commerce', 'To produce skilled business professionals', 'To provide quality commerce education'),
('economics', 'Economics', 'fa-chart-line', 'Department of Economics', 'To promote economic education', 'To provide quality economics education');

SELECT 'Database setup complete!' as status;
